application: bt-search
version: 1
runtime: php
api_version: 1

handlers:
- url: /
  script: index.php

- url: /index\.html
  script: index.php

- url: /public/css
  static_dir: public/css

- url: /public/js
  static_dir: public/js
  
- url: /public
  static_dir: public

- url: /tarms\.txt
  script: tarms.txt

- url: /stylesheets
  static_dir: stylesheets

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /admin/.*
  script: admin.php
  login: admin

- url: /.*
  script: not_found.php
